package provider

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

// Cloud-init defaults applied to zero values in CloudInitParams.
const (
	defaultToolServerPort = 8000
	defaultWidth          = 1280
	defaultHeight         = 800
	// defaultImageRef is a placeholder container image used only when the
	// caller leaves ImageRef empty. The real default is wired from config
	// (cfg.Image) by the control plane; C7 (pre-baking) governs which image a
	// session actually boots.
	defaultImageRef = "ghcr.io/backhand/ecu-image:latest"
)

// CloudInitParams are the inputs to RenderCloudInit. The control plane fills
// these per session at provision time.
type CloudInitParams struct {
	// ControlPlaneURL is the tunnel ingress the agent dials OUT to, e.g.
	// "wss://ecu.example.com/agent/connect" (production) or
	// "ws://10.0.0.1:8080/agent/connect" (local/dev). The agent needs this to
	// be reachable from the instance.
	ControlPlaneURL string

	// TunnelToken is the per-session secret the agent presents at
	// ControlPlaneURL. It is a hex token (safe in shell/YAML), but is quoted
	// defensively where it lands in shell commands anyway.
	TunnelToken string

	// ImageRef is the container image to run, e.g.
	// "ghcr.io/backhand/ecu-image:latest". Defaults to defaultImageRef.
	ImageRef string

	// ToolServerPort is the container's tool-server port. Defaults to
	// defaultToolServerPort (8000). It is published bound to 127.0.0.1 ONLY,
	// which is the localhost-only security property — the public IP never
	// listens.
	ToolServerPort int

	// Width and Height are the desktop resolution passed to the container.
	// Default 1280x800.
	Width, Height int

	// AgentBinaryURL is where the instance fetches the `ecu` binary from
	// (ECU_AGENT_BINARY_URL). C10 will supply real, arch-specific GitHub
	// Release URLs and the control plane may later self-serve its own binary;
	// for now this is a plain config value and cloud-init just curls it. There
	// is intentionally no fallback baked in here.
	AgentBinaryURL string
}

// withDefaults returns a copy of p with zero values replaced by defaults.
func (p CloudInitParams) withDefaults() CloudInitParams {
	if p.ToolServerPort == 0 {
		p.ToolServerPort = defaultToolServerPort
	}
	if p.Width == 0 {
		p.Width = defaultWidth
	}
	if p.Height == 0 {
		p.Height = defaultHeight
	}
	if p.ImageRef == "" {
		p.ImageRef = defaultImageRef
	}
	return p
}

// cloudInitTemplate is the #cloud-config rendered per session. It is
// deliberately minimal: its only jobs are install Docker, run the container
// (localhost-bound), install the `ecu` binary, and run the agent under a
// systemd unit so it restarts on crash. ALL tunnel/registration logic lives in
// the Go agent — there is no shell tunnel logic here.
//
// Shell-bound values are single-quoted to keep YAML/shell robust even though
// the tokens are hex and the URLs contain only ':' and '/'.
var cloudInitTemplate = template.Must(template.New("cloud-init").Parse(`#cloud-config
# ECU instance bootstrap. Generated by the control plane per session.
# Jobs: install Docker, run the computer-use container (localhost-bound only),
# install the ecu binary, run the reverse-tunnel agent as a systemd service.
package_update: true

write_files:
  - path: /etc/systemd/system/ecu-agent.service
    permissions: '0644'
    content: |
      [Unit]
      Description=ECU reverse-tunnel agent
      After=network-online.target docker.service
      Wants=network-online.target

      [Service]
      Type=simple
      ExecStart=/usr/local/bin/ecu --agent --control-plane '{{.ControlPlaneURL}}' --token '{{.TunnelToken}}' --tool-server 'http://127.0.0.1:{{.ToolServerPort}}'
      Restart=always
      RestartSec=2

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Install Docker via the official convenience script (current + minimal).
  - curl -fsSL https://get.docker.com | sh
  # Run the computer-use container. The tool-server port is published bound to
  # 127.0.0.1 ONLY: the public IP never listens, so the box has no inbound
  # public ports. The agent reaches the container over loopback.
  - docker run -d --name ecu --restart unless-stopped -e 'WIDTH={{.Width}}' -e 'HEIGHT={{.Height}}' -p '127.0.0.1:{{.ToolServerPort}}:{{.ToolServerPort}}' '{{.ImageRef}}'
  # Install the ecu binary and start the agent service.
  - curl -fsSL '{{.AgentBinaryURL}}' -o /usr/local/bin/ecu
  - chmod +x /usr/local/bin/ecu
  - systemctl daemon-reload
  - systemctl enable --now ecu-agent.service
`))

// RenderCloudInit renders a #cloud-config for the given params, applying
// defaults to zero values. The returned string always begins with the literal
// line "#cloud-config".
func RenderCloudInit(params CloudInitParams) (string, error) {
	p := params.withDefaults()
	if p.ControlPlaneURL == "" {
		return "", fmt.Errorf("cloudinit: ControlPlaneURL is required")
	}
	if p.TunnelToken == "" {
		return "", fmt.Errorf("cloudinit: TunnelToken is required")
	}
	if p.AgentBinaryURL == "" {
		return "", fmt.Errorf("cloudinit: AgentBinaryURL is required")
	}
	// Single quotes in shell-bound values would break the single-quoting; the
	// inputs (hex token, URLs, image ref, integers) never contain one, but
	// reject defensively rather than emit broken YAML.
	for _, v := range []string{p.ControlPlaneURL, p.TunnelToken, p.AgentBinaryURL, p.ImageRef} {
		if strings.Contains(v, "'") {
			return "", fmt.Errorf("cloudinit: value %q contains a single quote, which is not supported", v)
		}
	}
	var buf bytes.Buffer
	if err := cloudInitTemplate.Execute(&buf, p); err != nil {
		return "", fmt.Errorf("cloudinit: rendering template: %w", err)
	}
	return buf.String(), nil
}
